/**
 * /api/admin/signals — read-only signal history + result marking.
 *
 * On-demand model: signals are generated by users via POST /api/signals/request.
 * Admin can only view history and mark results (win/loss).
 *
 * GET    list (paginated)
 * PUT    update (mark result, toggle isActive)
 */
import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import type { Prisma } from "@/generated/prisma/client";

async function requireAdmin() {
  const session = await auth();
  if (!session || session.user.role !== "admin") return null;
  return session;
}

const VALID_RESULTS = ["pending", "win", "loss"] as const;

export async function GET(req: NextRequest) {
  const session = await requireAdmin();
  if (!session)
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { searchParams } = new URL(req.url);
  const page = Math.max(1, Math.min(10000, Number(searchParams.get("page") ?? 1) || 1));
  const limit = Math.max(1, Math.min(100, Number(searchParams.get("limit") ?? 50) || 50));

  const [signals, total] = await Promise.all([
    prisma.signal.findMany({
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * limit,
      take: limit,
      include: {
        createdBy: {
          select: { username: true, firstName: true, tier: true },
        },
      },
    }),
    prisma.signal.count(),
  ]);

  return NextResponse.json({ signals, total, page, limit });
}

export async function PUT(req: NextRequest) {
  const session = await requireAdmin();
  if (!session)
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  try {
    const body = await req.json();
    const { id, result, isActive } = body as {
      id?: string;
      result?: string;
      isActive?: boolean;
    };

    if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });

    const data: Prisma.SignalUpdateInput = {};
    if (result && (VALID_RESULTS as readonly string[]).includes(result)) {
      data.result = result as "pending" | "win" | "loss";
      data.closedAt = result === "pending" ? null : new Date();
    }
    if (typeof isActive === "boolean") data.isActive = isActive;

    const signal = await prisma.signal.update({ where: { id }, data });
    return NextResponse.json({ signal });
  } catch (err) {
    console.error("[admin/signals PUT]", err);
    return NextResponse.json({ error: "internal_error" }, { status: 500 });
  }
}
